package com.mistakenotebook.domain.subject;

import com.adminpro.framework.base.entity.BaseAuditEntity;
import com.adminpro.framework.jdbc.annotation.AutoGeneratedKey;
import com.adminpro.framework.jdbc.annotation.Column;
import com.adminpro.framework.jdbc.annotation.PrimaryKey;
import com.adminpro.framework.jdbc.annotation.Table;
import lombok.Data;

/**
 * 章节实体
 *
 * @author simon
 */
@Data
@Table(name = ChapterEntity.TABLE_NAME)
public class ChapterEntity extends BaseAuditEntity {
    private static final long serialVersionUID = 1L;

    public static final String TABLE_NAME = "MN_CHAPTER_TBL";

    public static final String COL_ID = "COL_ID";
    public static final String COL_SUBJECT_ID = "COL_SUBJECT_ID";
    public static final String COL_PARENT_ID = "COL_PARENT_ID";
    public static final String COL_NAME = "COL_NAME";
    public static final String COL_SORT_ORDER = "COL_SORT_ORDER";

    @AutoGeneratedKey
    @PrimaryKey
    @Column(name = COL_ID, type = Column.Type.STRING)
    private String id;

    @Column(name = COL_SUBJECT_ID, type = Column.Type.STRING)
    private String subjectId;

    @Column(name = COL_PARENT_ID, type = Column.Type.STRING)
    private String parentId;

    @Column(name = COL_NAME, type = Column.Type.STRING)
    private String name;

    @Column(name = COL_SORT_ORDER, type = Column.Type.INTEGER)
    private Integer sortOrder;
}
