package com.mistakenotebook.domain.subject;

import com.adminpro.framework.base.entity.BaseAuditEntity;
import com.adminpro.framework.jdbc.annotation.AutoGeneratedKey;
import com.adminpro.framework.jdbc.annotation.Column;
import com.adminpro.framework.jdbc.annotation.PrimaryKey;
import com.adminpro.framework.jdbc.annotation.Table;
import lombok.Data;

/**
 * 知识点实体
 *
 * @author simon
 */
@Data
@Table(name = KnowledgePointEntity.TABLE_NAME)
public class KnowledgePointEntity extends BaseAuditEntity {
    private static final long serialVersionUID = 1L;

    public static final String TABLE_NAME = "MN_KNOWLEDGE_POINT_TBL";

    public static final String COL_ID = "COL_ID";
    public static final String COL_CHAPTER_ID = "COL_CHAPTER_ID";
    public static final String COL_NAME = "COL_NAME";
    public static final String COL_DESCRIPTION = "COL_DESCRIPTION";

    @AutoGeneratedKey
    @PrimaryKey
    @Column(name = COL_ID, type = Column.Type.STRING)
    private String id;

    @Column(name = COL_CHAPTER_ID, type = Column.Type.STRING)
    private String chapterId;

    @Column(name = COL_NAME, type = Column.Type.STRING)
    private String name;

    @Column(name = COL_DESCRIPTION, type = Column.Type.STRING)
    private String description;
}
