package com.mistakenotebook.domain.subject;

import com.adminpro.framework.base.entity.BaseAuditEntity;
import com.adminpro.framework.jdbc.annotation.AutoGeneratedKey;
import com.adminpro.framework.jdbc.annotation.Column;
import com.adminpro.framework.jdbc.annotation.PrimaryKey;
import com.adminpro.framework.jdbc.annotation.Table;
import lombok.Data;

/**
 * 科目实体
 *
 * @author simon
 */
@Data
@Table(name = SubjectEntity.TABLE_NAME)
public class SubjectEntity extends BaseAuditEntity {
    private static final long serialVersionUID = 1L;

    public static final String TABLE_NAME = "MN_SUBJECT_TBL";

    public static final String COL_ID = "COL_ID";
    public static final String COL_NAME = "COL_NAME";
    public static final String COL_ICON = "COL_ICON";
    public static final String COL_SORT_ORDER = "COL_SORT_ORDER";

    @AutoGeneratedKey
    @PrimaryKey
    @Column(name = COL_ID, type = Column.Type.STRING)
    private String id;

    @Column(name = COL_NAME, type = Column.Type.STRING)
    private String name;

    @Column(name = COL_ICON, type = Column.Type.STRING)
    private String icon;

    @Column(name = COL_SORT_ORDER, type = Column.Type.INTEGER)
    private Integer sortOrder;
}
