package com.mistakenotebook.domain.review;

import com.adminpro.framework.base.entity.BaseAuditEntity;
import com.adminpro.framework.jdbc.annotation.AutoGeneratedKey;
import com.adminpro.framework.jdbc.annotation.Column;
import com.adminpro.framework.jdbc.annotation.PrimaryKey;
import com.adminpro.framework.jdbc.annotation.Table;
import lombok.Data;

import java.time.LocalDateTime;

/**
 * 复习记录实体
 *
 * @author simon
 */
@Data
@Table(name = ReviewRecordEntity.TABLE_NAME)
public class ReviewRecordEntity extends BaseAuditEntity {
    private static final long serialVersionUID = 1L;

    public static final String TABLE_NAME = "MN_REVIEW_RECORD_TBL";

    public static final String COL_ID = "COL_ID";
    public static final String COL_MISTAKE_ID = "COL_MISTAKE_ID";
    public static final String COL_USER_ID = "COL_USER_ID";
    public static final String COL_REVIEW_TIME = "COL_REVIEW_TIME";
    public static final String COL_REVIEW_RESULT = "COL_REVIEW_RESULT";
    public static final String COL_REVIEW_COUNT = "COL_REVIEW_COUNT";
    public static final String COL_NEXT_REVIEW_TIME = "COL_NEXT_REVIEW_TIME";
    public static final String COL_NOTES = "COL_NOTES";

    @AutoGeneratedKey
    @PrimaryKey
    @Column(name = COL_ID, type = Column.Type.STRING)
    private String id;

    @Column(name = COL_MISTAKE_ID, type = Column.Type.STRING)
    private String mistakeId;

    @Column(name = COL_USER_ID, type = Column.Type.STRING)
    private String userId;

    @Column(name = COL_REVIEW_TIME, type = Column.Type.DATE)
    private LocalDateTime reviewTime;

    @Column(name = COL_REVIEW_RESULT, type = Column.Type.STRING)
    private String reviewResult;

    @Column(name = COL_REVIEW_COUNT, type = Column.Type.INTEGER)
    private Integer reviewCount;

    @Column(name = COL_NEXT_REVIEW_TIME, type = Column.Type.DATE)
    private LocalDateTime nextReviewTime;

    @Column(name = COL_NOTES, type = Column.Type.STRING)
    private String notes;
}
