package com.mistakenotebook.domain.clazz;

import com.adminpro.framework.base.entity.BaseAuditEntity;
import com.adminpro.framework.jdbc.annotation.AutoGeneratedKey;
import com.adminpro.framework.jdbc.annotation.Column;
import com.adminpro.framework.jdbc.annotation.PrimaryKey;
import com.adminpro.framework.jdbc.annotation.Table;
import lombok.Data;

/**
 * 班级实体
 *
 * @author simon
 */
@Data
@Table(name = ClazzEntity.TABLE_NAME)
public class ClazzEntity extends BaseAuditEntity {
    private static final long serialVersionUID = 1L;

    public static final String TABLE_NAME = "MN_CLAZZ_TBL";

    public static final String COL_ID = "COL_ID";
    public static final String COL_NAME = "COL_NAME";
    public static final String COL_GRADE = "COL_GRADE";
    public static final String COL_TEACHER_ID = "COL_TEACHER_ID";
    public static final String COL_DESCRIPTION = "COL_DESCRIPTION";

    @AutoGeneratedKey
    @PrimaryKey
    @Column(name = COL_ID, type = Column.Type.STRING)
    private String id;

    @Column(name = COL_NAME, type = Column.Type.STRING)
    private String name;

    @Column(name = COL_GRADE, type = Column.Type.STRING)
    private String grade;

    @Column(name = COL_TEACHER_ID, type = Column.Type.STRING)
    private String teacherId;

    @Column(name = COL_DESCRIPTION, type = Column.Type.STRING)
    private String description;
}
