package com.mistakenotebook.domain.clazz;

import com.adminpro.framework.base.entity.BaseAuditEntity;
import com.adminpro.framework.jdbc.annotation.AutoGeneratedKey;
import com.adminpro.framework.jdbc.annotation.Column;
import com.adminpro.framework.jdbc.annotation.PrimaryKey;
import com.adminpro.framework.jdbc.annotation.Table;
import lombok.Data;

import java.time.LocalDateTime;

/**
 * 家长学生关联实体
 *
 * @author simon
 */
@Data
@Table(name = ParentStudentEntity.TABLE_NAME)
public class ParentStudentEntity extends BaseAuditEntity {
    private static final long serialVersionUID = 1L;

    public static final String TABLE_NAME = "MN_PARENT_STUDENT_TBL";

    public static final String COL_ID = "COL_ID";
    public static final String COL_PARENT_ID = "COL_PARENT_ID";
    public static final String COL_STUDENT_ID = "COL_STUDENT_ID";
    public static final String COL_RELATIONSHIP = "COL_RELATIONSHIP";
    public static final String COL_BIND_TIME = "COL_BIND_TIME";

    @AutoGeneratedKey
    @PrimaryKey
    @Column(name = COL_ID, type = Column.Type.STRING)
    private String id;

    @Column(name = COL_PARENT_ID, type = Column.Type.STRING)
    private String parentId;

    @Column(name = COL_STUDENT_ID, type = Column.Type.STRING)
    private String studentId;

    @Column(name = COL_RELATIONSHIP, type = Column.Type.STRING)
    private String relationship;

    @Column(name = COL_BIND_TIME, type = Column.Type.DATE)
    private LocalDateTime bindTime;
}
