package com.mistakenotebook.domain.clazz;

import com.adminpro.framework.base.entity.BaseAuditEntity;
import com.adminpro.framework.jdbc.annotation.AutoGeneratedKey;
import com.adminpro.framework.jdbc.annotation.Column;
import com.adminpro.framework.jdbc.annotation.PrimaryKey;
import com.adminpro.framework.jdbc.annotation.Table;
import lombok.Data;

import java.time.LocalDateTime;

/**
 * 学生班级关联实体
 *
 * @author simon
 */
@Data
@Table(name = StudentClazzEntity.TABLE_NAME)
public class StudentClazzEntity extends BaseAuditEntity {
    private static final long serialVersionUID = 1L;

    public static final String TABLE_NAME = "MN_STUDENT_CLAZZ_TBL";

    public static final String COL_ID = "COL_ID";
    public static final String COL_STUDENT_ID = "COL_STUDENT_ID";
    public static final String COL_CLAZZ_ID = "COL_CLAZZ_ID";
    public static final String COL_JOIN_TIME = "COL_JOIN_TIME";

    @AutoGeneratedKey
    @PrimaryKey
    @Column(name = COL_ID, type = Column.Type.STRING)
    private String id;

    @Column(name = COL_STUDENT_ID, type = Column.Type.STRING)
    private String studentId;

    @Column(name = COL_CLAZZ_ID, type = Column.Type.STRING)
    private String clazzId;

    @Column(name = COL_JOIN_TIME, type = Column.Type.DATE)
    private LocalDateTime joinTime;
}
