package com.mistakenotebook.domain.mistake;

import com.adminpro.framework.base.entity.BaseAuditEntity;
import com.adminpro.framework.jdbc.annotation.AutoGeneratedKey;
import com.adminpro.framework.jdbc.annotation.Column;
import com.adminpro.framework.jdbc.annotation.PrimaryKey;
import com.adminpro.framework.jdbc.annotation.Table;
import lombok.Data;

import java.time.LocalDateTime;

/**
 * 错题实体
 *
 * @author simon
 */
@Data
@Table(name = MistakeEntity.TABLE_NAME)
public class MistakeEntity extends BaseAuditEntity {
    private static final long serialVersionUID = 1L;

    public static final String TABLE_NAME = "MN_MISTAKE_TBL";

    public static final String COL_ID = "COL_ID";
    public static final String COL_USER_ID = "COL_USER_ID";
    public static final String COL_SUBJECT_ID = "COL_SUBJECT_ID";
    public static final String COL_CHAPTER_ID = "COL_CHAPTER_ID";
    public static final String COL_KNOWLEDGE_POINT_ID = "COL_KNOWLEDGE_POINT_ID";
    public static final String COL_TITLE = "COL_TITLE";
    public static final String COL_CONTENT = "COL_CONTENT";
    public static final String COL_CORRECT_ANSWER = "COL_CORRECT_ANSWER";
    public static final String COL_MY_ANSWER = "COL_MY_ANSWER";
    public static final String COL_ERROR_REASON = "COL_ERROR_REASON";
    public static final String COL_ERROR_ANALYSIS = "COL_ERROR_ANALYSIS";
    public static final String COL_SOURCE = "COL_SOURCE";
    public static final String COL_IMAGE_URLS = "COL_IMAGE_URLS";
    public static final String COL_MASTERY_STATUS = "COL_MASTERY_STATUS";
    public static final String COL_MASTERY_LEVEL = "COL_MASTERY_LEVEL";
    public static final String COL_DIFFICULTY = "COL_DIFFICULTY";
    public static final String COL_TAGS = "COL_TAGS";
    public static final String COL_REVIEW_COUNT = "COL_REVIEW_COUNT";
    public static final String COL_NEXT_REVIEW_TIME = "COL_NEXT_REVIEW_TIME";

    @AutoGeneratedKey
    @PrimaryKey
    @Column(name = COL_ID, type = Column.Type.STRING)
    private String id;

    @Column(name = COL_USER_ID, type = Column.Type.STRING)
    private String userId;

    @Column(name = COL_SUBJECT_ID, type = Column.Type.STRING)
    private String subjectId;

    @Column(name = COL_CHAPTER_ID, type = Column.Type.STRING)
    private String chapterId;

    @Column(name = COL_KNOWLEDGE_POINT_ID, type = Column.Type.STRING)
    private String knowledgePointId;

    @Column(name = COL_TITLE, type = Column.Type.STRING)
    private String title;

    @Column(name = COL_CONTENT, type = Column.Type.STRING)
    private String content;

    @Column(name = COL_CORRECT_ANSWER, type = Column.Type.STRING)
    private String correctAnswer;

    @Column(name = COL_MY_ANSWER, type = Column.Type.STRING)
    private String myAnswer;

    @Column(name = COL_ERROR_REASON, type = Column.Type.STRING)
    private String errorReason;

    @Column(name = COL_ERROR_ANALYSIS, type = Column.Type.STRING)
    private String errorAnalysis;

    @Column(name = COL_SOURCE, type = Column.Type.STRING)
    private String source;

    @Column(name = COL_IMAGE_URLS, type = Column.Type.STRING)
    private String imageUrls;

    @Column(name = COL_MASTERY_STATUS, type = Column.Type.STRING)
    private String masteryStatus;

    @Column(name = COL_MASTERY_LEVEL, type = Column.Type.INT)
    private Integer masteryLevel;

    @Column(name = COL_DIFFICULTY, type = Column.Type.STRING)
    private String difficulty;

    @Column(name = COL_TAGS, type = Column.Type.STRING)
    private String tags;

    @Column(name = COL_REVIEW_COUNT, type = Column.Type.INT)
    private Integer reviewCount;

    @Column(name = COL_NEXT_REVIEW_TIME, type = Column.Type.DATE)
    private LocalDateTime nextReviewTime;
}
